### PR TITLE
Fix invalid argument errer on device.Grab and device.Ungrab

### PR DESCRIPTION
**Pull request by indeedhat**
`ioctlEVIOCGRAB` was giving an "invalid argument" error when trying to Grab/Ungrab a device for exclusive access.

This was down to the ioctl code being generated with the size of a byte instead of the size of a nibble.

### CODE REVIEW

**Comment by gethiox** [comment]
I can confirm `Grab` and `Ungrab` still works with that change for `arm-v6` and `arm64` platforms.
```go
var nibble uint = 0x4
```
However, I don't think value `0x4` (it's just 4 in decimal) really matters, it seems like `uintptr` instead of `unsafe.Sizeof` works for you in that case, but from `ioctlMakeCode` function perspective it doesn't seem right.
All other ioctl calls are made in that way, is it only `ioctlEVIOCGRAB` that didn't work for you? What is your platform?

Also, compiled `main` binary should not be added to the repository.

Edit: I verified it for `amd64` under virtual machine, it returns "invalid argument" error, indeed

**Comment by indeedhat** [comment]
i tried it on two machines but both are amd64 running different flavors of endevouros (arch).

`ioctlEVIOCGRAB` is the only thing i have come across so far that doesn't work for me, reading of events works just fine regardless of if i grab exclusive access or not. i have only tried it with basic keystrokes and mouse movement but i see no reason why other things wouldn't work.

Totally missed the addition of the binary, sorry about that.

**Comment by gethiox** [comment]
You're right, I'm taking it back. 4 is the correct size value because C's int size is 4 bytes, Go's int is platform specific.
That's why it works fine on my `arm-v6` but didn't on `arm64`, unfortunately I omitted error handling in app that I'm currently developing and assumed it works there as well, and I've completely missed you're directly casting value to expected type, not getting pointer of it.

So I'll leave it up to repository maintainer, but in my opinion just changing type of `p` in `ioctlEVIOCGRAB` function signature from `int` to `int32` could be more readable as it explains where magic number 4 comes from.

Just for the record, there are also `ioctlEVIOCGREP` and `ioctlEVIOCSREP` functions which may share similar problem, but they are not being currently used in library.

**Comment by indeedhat** [comment]
that would probably make a lot more sense as an approach.

thanks for looking into it

**Comment by indeedhat** [comment]
improved fix included in a different pull request

**Pull request closed without merging**
